
AllCops:
  TargetRubyVersion: 2.5
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Max: 60
Layout/IndentationConsistency:
  EnforcedStyle: rails
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
