default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  host: localhost
  #host: postgresql
  port: 5433
  username: <%= ENV.fetch("DATABASE_USERNAME"){ 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: portfolio-dev

test:
  <<: *default
  database: portfolio-test

production:
  <<: *default
  database: portfolio-production
